### ISSUE TITLE
App crashes when trying to edit a member in roster

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#115]
Seems we have a problem

Steps to reproduce

Using staging:

- install the labtab;
- login to the labtab;
- select LabList section;
- find a program and copy the program's sku;
- login to test.wizbots.com as admin;
- select mentor section;
- select programs; 
- paste the copied sku from the labtab, to find the same program;
- click to find program;
- click on the program;
- scroll to the members list and add the member to the list;
- click update the program;
- return back to the labtab app;
- reinstall it;
- login to the labtab;
- find the program and select it;
- find the same member at the list and click to edit;
- App crashes, check attached logs

[bug.zip](https://github.com/wizbots/labtab/files/2844686/bug.zip)

**Comment by kapoorutd** [comment]
Hi @internetmosquito ,

I have debug and gone through your bug.zip file, and found the following things..

1. This crash is occurring due to, We are getting one of the student date_of_birth null from the api.
2. So please share the optional fields so that we can put null check on my end.
3. I have fixed this crash by adding the null check on my end.

**Comment by internetmosquito** [comment]
Sure, let me do that!

**Comment by internetmosquito** [comment]
This was released in previous version 1.8.6
