### ISSUE TITLE
Several issues with labtab v1.11.0

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#133]
Several issues reported in latest version:

1.- No connectivity regardless tablet was connected to WiFi
2.- Cupertino was having issues with the selection (check box of kids) and promotions. The kids were getting promoted by 2 levels or other kids were affected as well and showing a change in their levels even though they were not promoted.
3.- Charter Learning Center in San Carlos is not able to get into their camp as it does not show in the listed schools.

I'm attaching logs for the 2 tablets used, please check them and let me know. We're trying to reproduce the issues in our end as well

[miranda_labtab_logs.zip](https://github.com/wizbots/labtab/files/3305071/miranda_labtab_logs.zip)
[joshua_labtab_logs.zip](https://github.com/wizbots/labtab/files/3305072/joshua_labtab_logs.zip)

**Comment by internetmosquito** [comment]
More feedback

Miranda
Union Church of Cupertino
last week
any students she tried to promote were not accurately promoting those students by one level. Sometimes by 2 levels. Sometimes other kids would change levels that she did not promote.
Actions taken were to keep trying. It would typically happen every time she went out of that page and came back. Similar to the wizchips issue from before when it kept changing on its own and raising the number every time I came back into the page.

This week Miranda cannot log into her app after uninstalling and installing 1.11. All other devices were working with wifi but the tablet.

Joshua
Graham Mountain View
last week
school didn't show after selecting school, year, and season.

wizchip count did not work but is working now as of yesterday.

Union City Mark Green Sports Center
As of yesterday my videos stop uploading. The last 20 videos are still showing a red "uploading" message in the "video list."

Elizabeth
San Carlos 2
this week her school does not show. She cannot get access into her school to see kids

**Comment by kapoorutd** [comment]
@internetmosquito 
Thanks for sharing the feedback for previous build..
Here is the list of exceptions I am getting from the shared log files.

 [ 06-18 09:06:15.586  6119: 7366 W/System.err ]
 Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

 [ 06-18 09:04:44.942  6119: 7340 W/System.err ]
 java.net.UnknownHostException: Unable to resolve host "wizbots.com": No address associated with hostname

 [ 03-04 17:26:56.957  3343:11711 W/System.err ]
 java.net.ConnectException: Failed to connect to wizbots.com/45.33.14.140:443

 --------- beginning of main
 [ 03-04 21:04:45.062  3343:11152 W/System.err ]
 java.net.SocketException: Software caused connection abort

[ 03-15 17:39:04.811  3493: 4440 W/System.err ]
 Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)

 [ 06-14 11:21:45.908  4554: 4554 E/org.wizbots.labtab.util.LabTabUtil ]
 Error In Converting JsonToModel
 com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17 path $[1]
 	at com.google.gson.Gson.fromJson(Gson.java:902)

[ 05-13 16:18:37.599  3192: 4859 W/System.err ]
 java.net.NoRouteToHostException: No route to host

 [ 06-18 11:42:19.743  8392:10852 W/System.err ]
 javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.


 [ 06-14 11:40:58.258 12199:12199 E/org.wizbots.labtab.util.LabTabUtil ]
 Error In Converting JsonToModel
 com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 14 path $[1]
 	at com.google.gson.Gson.fromJson(Gson.java:902)
 	at com.google.gson.Gson.fromJson(Gson.java:852)
 	at com.google.gson.Gson.fromJson(Gson.java:801)
 	at org.wizbots.labtab.util.LabTabUtil.fromJson(LabTabUtil.java:71)



06-20 12:46:12.362 22725-22858/org.wizbots.labtab D/org.wizbots.labtab.retrofit.ConnectionUtil: Request Url : http://test.wizbots.com/api/tokens/ Request Body : {"encodedNames":["password","email"],"encodedValues":["robotics","judy%40wizbots.com"]}
06-20 12:46:13.193 22725-22858/org.wizbots.labtab D/org.wizbots.labtab.retrofit.ConnectionUtil: Response Code : 404
06-20 12:46:13.195 22725-22858/org.wizbots.labtab D/LoginRequester: createTokenResponse Failed, Response Code : 404

**After looking into the above log errors,  We are sharing our findings regarding the above list of exceptions as follows...**

1. Most of the exceptions occurs due to the server is not running.
2. Some security certificates were added in the back-end server side, that certificate we need to add this on app side also . So please let us update about the added security certificate in server side(if any).
3. We are getting invalid Gson string from the Api, that the reason we are getting JsonSyntaxException (May be some request or response gets changed).
4. We tried to reproduce above list of exceptions but unfortunately we are unable to log-in into the app because we are getting  **Response Code : 404** from the Api.
5. We tried to login into the app after pointing the app on production server url, but still we are unable to login in the app.

Please look into the above findings and update us about the needful changes.

**Comment by internetmosquito** [comment]
@kapoorutd That is correct, we updated the certificate, I'm attaching it 
[wizbots.com.zip](https://github.com/wizbots/labtab/files/3310704/wizbots.com.zip)

We are getting invalid Gson string from the Api, that the reason we are getting JsonSyntaxException (May be some request or response gets changed). -> Can you tell me what endpoint is causing this?

We tried to reproduce above list of exceptions but unfortunately we are unable to log-in into the app because we are getting Response Code : 404 from the Api.
We tried to login into the app after pointing the app on production server url, but still we are unable to login in the app. -> I'm checking but we also changed staging, you need it too I assume?

**Comment by BogdanSkrb** [comment]
@kapoorutd  I see you got 404 error, as @internetmosquito said we also changed staging.
Can you try using `https` protocol?
If not helps contact me via slack.

**Comment by internetmosquito** [comment]
[staging_ssl.tar.gz](https://github.com/wizbots/labtab/files/3311245/staging_ssl.tar.gz)

Attaching certificate for staging too @kapoorutd and this is strange, I made build for staging v1.11.0 with https://test.wizbots.com/api/ not sure why we see http in trace log?

**Comment by kapoorutd** [comment]
@internetmosquito 
Thanks for sharing the certificate files.

We have added the production server certificate in the app, now It's working fine on production server.

For staging server, We used this **"staging_ssl.tar.gz"** certificates but it's not working. We need  **.crt** certificate file used in staging server.

We have check-in the code in **m_zero** branch.

Please have a look into it and  provide the necessary staging server certificate file, because we are unable to login in the App.

@BogdanSkrb 
We have changed the staging server url from http to https, but its still I am getting the following Error

06-21 12:24:11.682 7533-7616/org.wizbots.labtab W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
06-21 12:24:11.685 7533-7616/org.wizbots.labtab W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
06-21 12:24:11.685 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
06-21 12:24:11.685 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
06-21 12:24:11.685 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
06-21 12:24:11.685 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
06-21 12:24:11.685 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
06-21 12:24:11.688 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
06-21 12:24:11.688 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
06-21 12:24:11.688 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
06-21 12:24:11.688 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
06-21 12:24:11.689 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:243)
06-21 12:24:11.689 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
06-21 12:24:11.689 7533-7616/org.wizbots.labtab W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by BogdanSkrb** [comment]
@kapoorutd did you tried to connect to the production server? Same error?

**Comment by kapoorutd** [comment]
@BogdanSkrb 
On production server, After adding the certificate, its working fine.

**Comment by BogdanSkrb** [comment]
@kapoorutd Happy to hear that.
about `staging_ssl.tar.gz`. according to this discussion:
https://community.letsencrypt.org/t/how-to-get-crt-and-key-files-from-i-just-have-pem-files/7348
There are the same.

**Comment by kapoorutd** [comment]
@internetmosquito 

Hope you are doing well..!

We have used the **"staging_ssl.tar.gz"** certificates in the project but it is not working as files are in link format. Attaching the screenshots for the reference.

So, please share the necessary certificates files, so that we can able to run the project on staging server.

[](https://drive.google.com/open?id=1avn8JdIdnEsMcHJkwC5jn5EhLiroj2ct)

[](https://drive.google.com/open?id=1gkhMSXqmWWivD7XeVI649U8x5ZZtZFcD)

**Comment by BogdanSkrb** [comment]
So sorry, I missed a folder. Here it is.
[cets_stagin.tar.gz](https://github.com/wizbots/labtab/files/3328950/cets_stagin.tar.gz)

**Comment by internetmosquito** [comment]
@kapoorutd any updates here?

**Comment by kapoorutd** [comment]
Let me check Tom on the same

**Comment by kapoorutd** [comment]
@BogdanSkrb 
Thanks for sharing the valid certificate files.
We have added the staging server certificate files in the project, Now its working fine on staging server.

@internetmosquito 

We have test for both Staging and Production server after adding the certificates files and found it's working smoothly now.

We have check-In the code in **m_zero** branch.
Please get a chance to look into it and confirm from your end.
